import { prisma } from "./lib/prisma";
import { z } from "zod";

// The frontend Zod settingsSchema
const settingsSchema = z.object({
  maintenanceMode: z.boolean(),
  maintenanceMessage: z
    .string()
    .trim()
    .min(1)
    .max(255),
  maintenanceEndTime: z
    .string()
    .refine((value) => !Number.isNaN(Date.parse(value)), 'Invalid date'),
  whatsappNumber: z
    .string()
    .trim()
    .max(20)
    .optional()
    .or(z.literal('')),
  internshipHeroTitle: z.string().trim().min(1).max(120),
  internshipHeroSubtitle: z.string().trim().min(1).max(140),
  internshipHeroDescription: z.string().trim().min(1).max(1200),
  internshipHeroImageUrl: z.string().trim().url().or(z.literal('')),
  internshipIntroTitle: z.string().trim().min(1).max(140),
  internshipIntroDescription: z.string().trim().min(1).max(2000),
  internshipApproachTitle: z.string().trim().min(1).max(140),
  internshipApproachDescription: z.string().trim().min(1).max(2000),
  internshipCardOneValue: z.string().trim().min(1).max(20),
  internshipCardOneTitle: z.string().trim().min(1).max(140),
  internshipCardOneDescription: z.string().trim().min(1).max(900),
  internshipCardTwoValue: z.string().trim().min(1).max(20),
  internshipCardTwoTitle: z.string().trim().min(1).max(140),
  internshipCardTwoDescription: z.string().trim().min(1).max(900),
  internshipCardThreeValue: z.string().trim().min(1).max(20),
  internshipCardThreeTitle: z.string().trim().min(1).max(140),
  internshipCardThreeDescription: z.string().trim().min(1).max(900),
  internshipGalleryTitle: z.string().trim().min(1).max(140),
  internshipGalleryImageUrls: z.string().trim().min(1).max(6000),
  internshipTestimonialsTitle: z.string().trim().min(1).max(140),
  internshipClosingTitle: z.string().trim().min(1).max(180),
  internshipClosingContent: z.string().trim().min(1).max(5000),
  internshipApplyEmail: z.string().trim().email(),
  internshipPrograms: z.array(z.object({
    id: z.string(),
    title: z.string().trim().max(200),
    icon: z.string().trim().max(100).optional().or(z.literal('')),
    points: z.array(z.string().trim().max(400)),
    learnMoreLink: z.string().trim().max(1000).optional().or(z.literal('')),
    colorTheme: z.string().trim().max(50).optional().or(z.literal('')),
  })).optional(),
  internshipTestimonials: z.array(z.object({
    id: z.string(),
    name: z.string().trim().max(200),
    content: z.string().trim().max(2000),
    role: z.string().trim().max(200).optional().or(z.literal('')),
    avatarUrl: z.string().trim().max(2000).optional().or(z.literal('')),
  })).optional(),
  labsHeroTitle: z.string().trim().min(1).max(120),
  labsHeroSubtitle: z.string().trim().min(1).max(140),
  labsHeroDescription: z.string().trim().min(1).max(1200),
  labsHeroImageUrl: z.string().trim().url().or(z.literal('')),
  labsPageTitle: z.string().trim().min(1).max(140),
  labsPageSubtitle: z.string().trim().min(1).max(140),
  labsHeroBtn1Text: z.string().trim().min(1).max(40),
  labsHeroBtn2Text: z.string().trim().min(1).max(40),
  labsIntroDescription: z.string().trim().min(1).max(2000),
  labsIntroImageUrl: z.string().trim().url().or(z.literal('')),
  labsIntroBtnText: z.string().trim().min(1).max(40),
  labsIntroFeature1Title: z.string().trim().min(1).max(80),
  labsIntroFeature1Desc: z.string().trim().min(1).max(200),
  labsIntroFeature2Title: z.string().trim().min(1).max(80),
  labsIntroFeature2Desc: z.string().trim().min(1).max(200),
  labsIntroFeature3Title: z.string().trim().min(1).max(80),
  labsIntroFeature3Desc: z.string().trim().min(1).max(200),
  labsIntroFeature4Title: z.string().trim().min(1).max(80),
  labsIntroFeature4Desc: z.string().trim().min(1).max(200),
  labsCareersTitle: z.string().trim().min(1).max(140),
  labsCareersDescription: z.string().trim().min(1).max(2000),
  labsCareersBtnText: z.string().trim().min(1).max(40),
  labsCtaTitle: z.string().trim().min(1).max(140),
  labsCtaDescription: z.string().trim().min(1).max(2000),
  labsCtaBtnText: z.string().trim().min(1).max(40),
  labsSpotlights: z.array(z.object({
    id: z.string(),
    badge: z.string().trim().min(1).max(60),
    title: z.string().trim().min(1).max(140),
    description: z.string().trim().min(1).max(2000),
    imageUrl: z.string().trim().url().or(z.literal('')),
    list: z.string().trim().max(4000),
    projectSlug: z.string().trim().max(160).or(z.literal('')),
  })),

  labsInitiatives: z.array(z.object({
    id: z.string(),
    badge: z.string().trim().max(60).optional().or(z.literal('')),
    title: z.string().trim().max(200),
    description: z.string().trim().max(2000),
    imageUrl: z.string().trim().max(2000).optional().or(z.literal('')),
    link: z.string().trim().max(2000).optional().or(z.literal('')),
    btnText: z.string().trim().max(100).optional().or(z.literal('')),
    layout: z.string().trim().max(100),
  })).optional(),
  labsRigorTitle: z.string().trim().max(200).optional().or(z.literal('')),
  labsRigorDescription: z.string().trim().max(4000).optional().or(z.literal('')),
  labsRigorPoints: z.array(z.string().trim().max(1000)).optional(),
  labsRigorImage: z.string().trim().max(2000).optional().or(z.literal('')),
  labsMentorshipTitle: z.string().trim().max(200).optional().or(z.literal('')),
  labsMentorshipDescription: z.string().trim().max(4000).optional().or(z.literal('')),
  labsMentorshipImage: z.string().trim().max(2000).optional().or(z.literal('')),
  labsMentorshipQuote: z.string().trim().max(2000).optional().or(z.literal('')),
  labsMentorshipQuoteAuthor: z.string().trim().max(200).optional().or(z.literal('')),
  labsMentorshipQuoteRole: z.string().trim().max(200).optional().or(z.literal('')),
  labsMentorshipQuoteAvatar: z.string().trim().max(2000).optional().or(z.literal('')),

  servicesHeroTitle: z.string().trim().min(1).max(140),
  servicesHeroGradient: z.string().trim().min(1).max(140),
  servicesHeroBadge: z.string().trim().min(1).max(100),
  servicesHeroDescription: z.string().trim().min(1).max(2000),
  servicesHeroBtn1Text: z.string().trim().min(1).max(80),
  servicesHeroBtn1Url: z.string().trim().min(1).max(200),
  servicesHeroBtn2Text: z.string().trim().min(1).max(80),
  servicesHeroBtn2Url: z.string().trim().min(1).max(200),
  servicesCapTitle: z.string().trim().min(1).max(140),
  servicesCapHighlight: z.string().trim().min(1).max(140),
  servicesCapBadge: z.string().trim().min(1).max(100),
  servicesCapDescription: z.string().trim().min(1).max(2000),
  servicesProcessTitle: z.string().trim().min(1).max(140),
  servicesProcessBadge: z.string().trim().min(1).max(100),
  servicesProcessDescription: z.string().trim().min(1).max(2000),
  servicesProcessSteps: z.array(z.object({
    step: z.string().trim().min(1).max(20),
    title: z.string().trim().min(1).max(140),
    desc: z.string().trim().min(1).max(1200),
  })),
  servicesWhyTitle: z.string().trim().min(1).max(140),
  servicesWhyBadge: z.string().trim().min(1).max(100),
  servicesWhyDescription: z.string().trim().min(1).max(2000),
  servicesWhyItems: z.array(z.object({
    title: z.string().trim().min(1).max(140),
    description: z.string().trim().min(1).max(1200),
  })),
  servicesWhyPromiseBadge: z.string().trim().min(1).max(100),
  servicesWhyPromiseQuote: z.string().trim().min(1).max(1200),
  servicesWhyPromiseAuthor: z.string().trim().min(1).max(140),
  servicesWhyPromiseSub: z.string().trim().min(1).max(140),
  servicesWhyPromiseTags: z.string().trim().max(2000),
  servicesCtaTitle: z.string().trim().min(1).max(200),
  servicesCtaBadge: z.string().trim().min(1).max(100),
  servicesCtaDescription: z.string().trim().min(1).max(2000),
  servicesCtaBtn1Text: z.string().trim().min(1).max(80),
  servicesCtaBtn1Url: z.string().trim().min(1).max(200),
  servicesCtaBtn2Text: z.string().trim().min(1).max(80),
  servicesCtaBtn2Url: z.string().trim().min(1).max(200),
  servicesWhatTitle: z.string().trim().min(1).max(200),
  servicesWhatDescription: z.string().trim().min(1).max(2000),
  servicesWhatFeatures: z.array(z.object({
    title: z.string().trim().min(1).max(140),
    desc: z.string().trim().min(1).max(1200),
    icon: z.string().trim().min(1).max(100),
  })).min(1).max(4),
  servicesWhatImages: z.array(z.string().trim().url().or(z.literal(''))).min(4).max(4),

  homeSolutionsTitle: z.string().trim().max(200).optional(),
  homeSolutionsBadge: z.string().trim().max(100).optional(),
  homeSolutionsDescription: z.string().trim().max(2000).optional(),
  homeSolutionsItems: z.array(z.string()).optional(),

  homeServicesTitle: z.string().trim().max(200).optional().or(z.literal('')),
  homeServicesBadge: z.string().trim().max(100).optional().or(z.literal('')),
  homeRecentWorkTitle: z.string().trim().max(200).optional().or(z.literal('')),
  homeRecentWorkBadge: z.string().trim().max(100).optional().or(z.literal('')),
  homeRecentWorkItems: z.array(z.object({
    id: z.string(),
    title: z.string().trim().max(200),
    description: z.string().trim().max(1200),
    category: z.string().trim().max(100),
    imageUrl: z.string().trim().max(2000),
    badgeClass: z.string().trim().max(200).optional().or(z.literal('')),
  })).optional(),

  homeVideoUrl: z.string().trim().url().or(z.literal('')),
  homeVideoEnabled: z.boolean(),

  contactHeroTitle: z.string().trim().min(1).max(200),
  contactHeroDescription: z.string().trim().min(1).max(2000),
  contactGlobalPresenceBadge: z.string().trim().min(1).max(100),
  contactGlobalPresenceTitle: z.string().trim().min(1).max(200),

  contactBranch1Title: z.string().trim().max(140).optional(),
  contactBranch1Address: z.string().trim().max(800).optional(),
  contactBranch1MapLink: z.string().trim().max(1000).optional(),
  contactBranch1LatLong: z.string().trim().max(200).optional(),
  contactBranch1MarkerX: z.string().trim().or(z.number()).optional(),
  contactBranch1MarkerY: z.string().trim().or(z.number()).optional(),

  contactBranch2Title: z.string().trim().max(140).optional(),
  contactBranch2Address: z.string().trim().max(800).optional(),
  contactBranch2MapLink: z.string().trim().max(1000).optional(),
  contactBranch2LatLong: z.string().trim().max(200).optional(),
  contactBranch2MarkerX: z.string().trim().or(z.number()).optional(),
  contactBranch2MarkerY: z.string().trim().or(z.number()).optional(),

  contactBranch3Title: z.string().trim().max(140).optional(),
  contactBranch3Address: z.string().trim().max(800).optional(),
  contactBranch3MapLink: z.string().trim().max(1000).optional(),
  contactBranch3LatLong: z.string().trim().max(200).optional(),
  contactBranch3MarkerX: z.string().trim().or(z.number()).optional(),
  contactBranch3MarkerY: z.string().trim().or(z.number()).optional(),

  contactSupportTitle: z.string().trim().min(1).max(200),
  contactSupportDescription: z.string().trim().min(1).max(2000),
  contactSupportItem1Title: z.string().trim().min(1).max(140),
  contactSupportItem1Desc: z.string().trim().min(1).max(400),
  contactSupportItem1Link: z.string().trim().min(1).max(1000),
  contactSupportItem2Title: z.string().trim().min(1).max(140),
  contactSupportItem2Desc: z.string().trim().min(1).max(400),
  contactSupportItem2Link: z.string().trim().min(1).max(1000),
  contactSupportItem3Title: z.string().trim().min(1).max(140),
  contactSupportItem3Desc: z.string().trim().min(1).max(400),
  contactSupportItem3Status: z.string().trim().min(1).max(100),

  contactFaqTitle: z.string().trim().min(1).max(200),
  contactFaqDescription: z.string().trim().min(1).max(2000),
  contactFaq1Question: z.string().trim().min(1).max(400),
  contactFaq1Answer: z.string().trim().min(1).max(2000),
  contactFaq2Question: z.string().trim().min(1).max(400),
  contactFaq2Answer: z.string().trim().min(1).max(2000),
  contactFaq3Question: z.string().trim().min(1).max(400),
  contactFaq3Answer: z.string().trim().min(1).max(2000),

  contactBranches: z.array(z.object({
    id: z.string(),
    title: z.string().trim().max(140).optional().or(z.literal('')),
    address: z.string().trim().max(800).optional().or(z.literal('')),
    mapLink: z.string().trim().max(1000).optional().or(z.literal('')),
    latLong: z.string().trim().max(200).optional().or(z.literal('')),
    markerX: z.number(),
    markerY: z.number(),
  })).optional(),

  adminNotificationEmail: z.string().trim().email().or(z.literal('')),

  smtpHost: z.string().trim().max(255).optional().or(z.literal('')),
  smtpPort: z.string().trim().max(10).optional().or(z.literal('')),
  smtpUser: z.string().trim().max(255).optional().or(z.literal('')),
  smtpPass: z.string().trim().max(255).optional().or(z.literal('')),
  smtpFrom: z.string().trim().email().optional().or(z.literal('')),
});

const DEFAULT_VALUES = {
  maintenanceMode: false,
  maintenanceMessage: 'We are currently under maintenance. Please check back soon.',
  maintenanceEndTime: new Date().toISOString(),
  whatsappNumber: '',
  homeServicesTitle: '',
  homeServicesBadge: '',
  homeRecentWorkTitle: '',
  homeRecentWorkBadge: '',
  homeRecentWorkItems: [],
  internshipHeroTitle: 'Internship Program',
  internshipHeroSubtitle: 'Learn by Building Real Products',
  internshipHeroDescription: 'Gain practical experience through hands-on projects, code reviews, and team collaboration.',
  internshipHeroImageUrl: '',
  internshipIntroTitle: 'Internship - IBT',
  internshipIntroDescription: 'Get skilled with industry experts who guide you to sharpen technical and professional capabilities.',
  internshipApproachTitle: 'Our Approach to Internship',
  internshipApproachDescription: 'Our 70-20-10 style framework balances implementation practice, collaborative learning, and focused mentoring.',
  internshipCardOneValue: '70',
  internshipCardOneTitle: 'Experiential Learning',
  internshipCardOneDescription: 'Focus on project-based implementation.',
  internshipCardTwoValue: '20',
  internshipCardTwoTitle: 'Social Learning',
  internshipCardTwoDescription: 'Collaborate with peers and participate in review sessions.',
  internshipCardThreeValue: '10',
  internshipCardThreeTitle: 'Mentored Growth',
  internshipCardThreeDescription: 'Get guided feedback from mentors on architecture and quality.',
  internshipGalleryTitle: 'How We Do It',
  internshipGalleryImageUrls: '[]',
  internshipTestimonialsTitle: 'Testimonials',
  internshipClosingTitle: 'Build Your Career with IBT',
  internshipClosingContent: 'At I-BACUS-TECH, we provide practical, industry-aligned training.',
  internshipApplyEmail: 'hr@ibacustech.com',
  labsHeroTitle: 'IBT LABS',
  labsHeroSubtitle: 'ENGINEERING THE FUTURE',
  labsHeroDescription: 'Empowering the next generation of researchers and engineers through precision-led skill development and forward-thinking technological innovation.',
  labsHeroImageUrl: '',
  labsPageTitle: 'I-BACUS-TECH LABS',
  labsPageSubtitle: 'Skill Development Program',
  labsHeroBtn1Text: 'EXPLORE PROGRAMS',
  labsHeroBtn2Text: 'TECHNICAL SPECS',
  labsIntroDescription: 'Our intensive, project-based curriculum is designed to bridge the gap between academic theory and industry application, providing a high-rigor environment for aspiring tech professionals.',
  labsIntroImageUrl: '',
  labsIntroBtnText: 'APPLY NOW',
  labsIntroFeature1Title: 'Project-Based',
  labsIntroFeature1Desc: 'Real-world challenges and technical deliverables.',
  labsIntroFeature2Title: 'Unpaid Opportunity',
  labsIntroFeature2Desc: 'Focused on pure skill acquisition and mentorship.',
  labsIntroFeature3Title: 'Mentorship',
  labsIntroFeature3Desc: 'Guided by industry veterans and research leads.',
  labsIntroFeature4Title: 'Certification',
  labsIntroFeature4Desc: 'Accredited recognition of laboratory proficiency.',
  labsCareersTitle: 'Careersheets',
  labsCareersDescription: 'The ultimate architectural tool for job seekers. Build resumes with engineering precision, track applications, and optimize your professional footprint for high-tech recruitment.',
  labsCareersBtnText: 'Sign in to Dashboard',
  labsCtaTitle: 'Have a Breakthrough Idea?',
  labsCtaDescription: 'IBT Labs is an incubator for intellectual rigor. We invite students and researchers to share their innovative technical concepts for collaborative potential.',
  labsCtaBtnText: 'Collaborate',
  labsSpotlights: [],
  servicesHeroTitle: 'Services Built for',
  servicesHeroGradient: 'Enterprise Scale',
  servicesHeroBadge: 'What We Offer',
  servicesHeroDescription: 'We architect bespoke technology solutions — from cloud infrastructure to AI-powered platforms — designed to give your business an unbeatable competitive edge.',
  servicesHeroBtn1Text: 'Start a Project',
  servicesHeroBtn1Url: '/contact',
  servicesHeroBtn2Text: 'Our Work',
  servicesHeroBtn2Url: '/about',
  servicesCapTitle: 'Everything You Need to',
  servicesCapHighlight: 'Win',
  servicesCapBadge: 'Our Capabilities',
  servicesCapDescription: 'End-to-end solutions across technology, design, and strategy to accelerate your growth.',
  servicesProcessTitle: 'How We Deliver Excellence',
  servicesProcessBadge: 'Our Process',
  servicesProcessDescription: '',
  servicesProcessSteps: [
    { step: '01', title: 'Discovery', desc: 'We deep-dive into your business goals, technical landscape, and user needs to craft a tailored strategy.' },
    { step: '02', title: 'Architecture', desc: 'Our senior architects design scalable, secure solutions aligned with your long-term growth roadmap.' },
    { step: '03', title: 'Build & Iterate', desc: 'Agile sprints with continuous delivery — you see progress every two weeks, not just at the end.' },
    { step: '04', title: 'Launch & Scale', desc: 'Production-grade deployment with monitoring, support, and optimization built in from day one.' },
  ],
  servicesWhyTitle: 'Built Different, Delivering More',
  servicesWhyBadge: 'Why IBT',
  servicesWhyDescription: "We don't just write code — we partner with you to understand your business deeply and engineer solutions that outlast trends and scale with your ambition.",
  servicesWhyItems: [
    { title: 'Senior-led teams', description: 'Senior-led teams with deep domain expertise.' },
    { title: 'Transparent delivery', description: 'Transparent delivery with weekly progress reports.' },
    { title: 'Security-first', description: 'Security-first architecture on every project.' },
    { title: 'Post-launch support', description: 'Post-launch support & continuous optimization.' },
    { title: 'Flexible models', description: 'Flexible engagement models to match your needs.' },
  ],
  servicesWhyPromiseBadge: 'Our Promise',
  servicesWhyPromiseQuote: 'We treat your business goals as our own — your success is the only metric that matters.',
  servicesWhyPromiseAuthor: 'I-Bacus Tech',
  servicesWhyPromiseSub: 'Technology Partner',
  servicesWhyPromiseTags: '200+ Projects\n99% CSAT\n12+ Years',
  servicesCtaTitle: "Let's Build Something Remarkable Together",
  servicesCtaBadge: 'Ready to Begin?',
  servicesCtaDescription: 'Schedule a free architecture consultation with our senior engineers and discover the optimal strategy for your next phase of growth.',
  servicesCtaBtn1Text: 'Schedule Consultation',
  servicesCtaBtn1Url: '/contact',
  servicesCtaBtn2Text: 'View Case Studies',
  servicesCtaBtn2Url: '/about',
  servicesWhatTitle: 'What We Do',
  servicesWhatDescription: '',
  servicesWhatFeatures: [],
  servicesWhatImages: [],
  homeSolutionsTitle: '',
  homeSolutionsBadge: '',
  homeSolutionsDescription: '',
  homeSolutionsItems: [],
  contactHeroTitle: 'Get in Touch with our Global Teams',
  contactHeroDescription: 'Whether you are looking to architect custom enterprise software, scale your cloud infrastructure, or explore standard R&D partnerships, our team is ready to map your technical roadmap.',
  contactGlobalPresenceBadge: 'GLOBAL COVERAGE',
  contactGlobalPresenceTitle: 'IBT Interactive Command Centers',
  contactBranch1Title: 'Coimbatore Headquarters',
  contactBranch1Address: 'IBT Tower, 45, Residency Road, Coimbatore, Tamil Nadu, 641018',
  contactBranch1MapLink: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3916.3175853245404!2d76.9587422!3d11.0168445!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba859af2f973b7f%3A0x2fe26c6d48c8b417!2sCoimbatore%2C%20Tamil%20Nadu!5e0!3m2!1sen!2sin!4v1684343423452!5m2!1sen!2sin',
  contactBranch1LatLong: '11.0168° N, 76.9558° E',
  contactBranch1MarkerX: 62.5,
  contactBranch1MarkerY: 41.2,
  contactBranch2Title: 'Chennai Innovation Lab',
  contactBranch2Address: 'Prestige Polygon, 471, Anna Salai, Nandanam, Chennai, Tamil Nadu, 600035',
  contactBranch2MapLink: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3886.8202353139366!2d80.2437637!3d13.0452332!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba859af2f973b7f%3A0x2fe26c6d48c8b417!2sChennai%2C%20Tamil%20Nadu!5e0!3m2!1sen!2sin!4v1684343423452!5m2!1sen!2sin',
  contactBranch2LatLong: '13.0452° N, 80.2438° E',
  contactBranch2MarkerX: 68.2,
  contactBranch2MarkerY: 34.8,
  contactBranch3Title: 'Bengaluru R&D Hub',
  contactBranch3Address: 'WeWork Galaxy, 43, Residency Road, Bengaluru, Karnataka, 560025',
  contactBranch3MapLink: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.9256910168453!2d77.6087422!3d12.9718445!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba859af2f973b7f%3A0x2fe26c6d48c8b417!2sBengaluru%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1684343423452!5m2!1sen!2sin',
  contactBranch3LatLong: '12.9718° N, 77.5946° E',
  contactBranch3MarkerX: 59.4,
  contactBranch3MarkerY: 43.6,
  contactSupportTitle: 'Dedicated Pipelines',
  contactSupportDescription: 'Whether you want a corporate briefing, look for internship validation, or experience a network event, we have a pipeline ready.',
  contactSupportItem1Title: 'Request standard project exploration / demo',
  contactSupportItem1Desc: 'Map out a secure proof of concept with our architects. Average turnaround is 24 hours.',
  contactSupportItem1Link: 'mailto:projects@ibacustech.com',
  contactSupportItem2Title: 'Apply for internship & research cohorts',
  contactSupportItem2Desc: 'Get structural hands-on engineering training inside our labs. Submit technical profile.',
  contactSupportItem2Link: 'mailto:careers@ibacustech.com',
  contactSupportItem3Title: 'Corporate operations / SLA support line',
  contactSupportItem3Desc: 'For active production service degradation support.',
  contactSupportItem3Status: '+91 94437 20267',
  contactFaqTitle: 'Frequently Answered Inquiries',
  contactFaqDescription: 'A direct compilation of architectural, structural, and onboarding paradigms for rapid assessment.',
  contactFaq1Question: 'What standard engagement parameters do you require?',
  contactFaq1Answer: 'We operate through discovery sprints to understand scope constraints, deliverables, and SLAs prior to standard contract commitment.',
  contactFaq2Question: 'Can your teams work within hybrid operational timezones?',
  contactFaq2Answer: 'Yes. Our staff coordinate globally using redundant asynchronous channels and overlap sync blocks tailored to our partners.',
  contactFaq3Question: 'How secure is the client-side master sandbox interface?',
  contactFaq3Answer: 'All access endpoints use military-grade HTTPS/TLS standards, coupled with modern role-based audit telemetry to map modifications.',
  contactBranches: [],
  adminNotificationEmail: '',
  smtpHost: '',
  smtpPort: '',
  smtpUser: '',
  smtpPass: '',
  smtpFrom: '',
};

const SETTINGS_KEYS = {
  MAINTENANCE_MODE: 'maintenance_mode',
  MAINTENANCE_MESSAGE: 'maintenance_message',
  MAINTENANCE_END_TIME: 'maintenance_end_time',
  WHATSAPP_NUMBER: 'whatsapp_number',
  INTERNSHIP_HERO_TITLE: 'internship_hero_title',
  INTERNSHIP_HERO_SUBTITLE: 'internship_hero_subtitle',
  INTERNSHIP_HERO_DESCRIPTION: 'internship_hero_description',
  INTERNSHIP_HERO_IMAGE_URL: 'internship_hero_image_url',
  INTERNSHIP_INTRO_TITLE: 'internship_intro_title',
  INTERNSHIP_INTRO_DESCRIPTION: 'internship_intro_description',
  INTERNSHIP_APPROACH_TITLE: 'internship_approach_title',
  INTERNSHIP_APPROACH_DESCRIPTION: 'internship_approach_description',
  INTERNSHIP_CARD_ONE_VALUE: 'internship_card_one_value',
  INTERNSHIP_CARD_ONE_TITLE: 'internship_card_one_title',
  INTERNSHIP_CARD_ONE_DESCRIPTION: 'internship_card_one_description',
  INTERNSHIP_CARD_TWO_VALUE: 'internship_card_two_value',
  INTERNSHIP_CARD_TWO_TITLE: 'internship_card_two_title',
  INTERNSHIP_CARD_TWO_DESCRIPTION: 'internship_card_two_description',
  INTERNSHIP_CARD_THREE_VALUE: 'internship_card_three_value',
  INTERNSHIP_CARD_THREE_TITLE: 'internship_card_three_title',
  INTERNSHIP_CARD_THREE_DESCRIPTION: 'internship_card_three_description',
  INTERNSHIP_GALLERY_TITLE: 'internship_gallery_title',
  INTERNSHIP_GALLERY_IMAGE_URLS: 'internship_gallery_image_urls',
  INTERNSHIP_TESTIMONIALS_TITLE: 'internship_testimonials_title',
  INTERNSHIP_CLOSING_TITLE: 'internship_closing_title',
  INTERNSHIP_CLOSING_CONTENT: 'internship_closing_content',
  INTERNSHIP_APPLY_EMAIL: 'internship_apply_email',
  INTERNSHIP_PROGRAMS: 'internship_programs',
  INTERNSHIP_TESTIMONIALS: 'internship_testimonials',
  LABS_HERO_TITLE: 'labs_hero_title',
  LABS_HERO_SUBTITLE: 'labs_hero_subtitle',
  LABS_HERO_DESCRIPTION: 'labs_hero_description',
  LABS_HERO_IMAGE_URL: 'labs_hero_image_url',
  LABS_PAGE_TITLE: 'labs_page_title',
  LABS_PAGE_SUBTITLE: 'labs_page_subtitle',
  LABS_HERO_BTN1_TEXT: 'labs_hero_btn1_text',
  LABS_HERO_BTN2_TEXT: 'labs_hero_btn2_text',
  LABS_INTRO_DESCRIPTION: 'labs_intro_description',
  LABS_INTRO_IMAGE_URL: 'labs_intro_image_url',
  LABS_INTRO_BTN_TEXT: 'labs_intro_btn_text',
  LABS_INTRO_FEATURE1_TITLE: 'labs_intro_feature1_title',
  LABS_INTRO_FEATURE1_DESC: 'labs_intro_feature1_desc',
  LABS_INTRO_FEATURE2_TITLE: 'labs_intro_feature2_title',
  LABS_INTRO_FEATURE2_DESC: 'labs_intro_feature2_desc',
  LABS_INTRO_FEATURE3_TITLE: 'labs_intro_feature3_title',
  LABS_INTRO_FEATURE3_DESC: 'labs_intro_feature3_desc',
  LABS_INTRO_FEATURE4_TITLE: 'labs_intro_feature4_title',
  LABS_INTRO_FEATURE4_DESC: 'labs_intro_feature4_desc',
  LABS_SPOTLIGHTS: 'labs_spotlights',
  LABS_CAREERS_TITLE: 'labs_careers_title',
  LABS_CAREERS_DESCRIPTION: 'labs_careers_description',
  LABS_CAREERS_BTN_TEXT: 'labs_careers_btn_text',
  LABS_CTA_TITLE: 'labs_cta_title',
  LABS_CTA_DESCRIPTION: 'labs_cta_description',
  LABS_CTA_BTN_TEXT: 'labs_cta_btn_text',
  LABS_INITIATIVES: 'labs_initiatives',
  LABS_RIGOR_TITLE: 'labs_rigor_title',
  LABS_RIGOR_DESCRIPTION: 'labs_rigor_description',
  LABS_RIGOR_POINTS: 'labs_rigor_points',
  LABS_RIGOR_IMAGE: 'labs_rigor_image',
  LABS_MENTORSHIP_TITLE: 'labs_mentorship_title',
  LABS_MENTORSHIP_DESCRIPTION: 'labs_mentorship_description',
  LABS_MENTORSHIP_IMAGE: 'labs_mentorship_image',
  LABS_MENTORSHIP_QUOTE: 'labs_mentorship_quote',
  LABS_MENTORSHIP_QUOTE_AUTHOR: 'labs_mentorship_quote_author',
  LABS_MENTORSHIP_QUOTE_ROLE: 'labs_mentorship_quote_role',
  LABS_MENTORSHIP_QUOTE_AVATAR: 'labs_mentorship_quote_avatar',
  SERVICES_HERO_TITLE: 'services_hero_title',
  SERVICES_HERO_GRADIENT: 'services_hero_gradient',
  SERVICES_HERO_BADGE: 'services_hero_badge',
  SERVICES_HERO_DESCRIPTION: 'services_hero_description',
  SERVICES_HERO_BTN1_TEXT: 'services_hero_btn1_text',
  SERVICES_HERO_BTN1_URL: 'services_hero_btn1_url',
  SERVICES_HERO_BTN2_TEXT: 'services_hero_btn2_text',
  SERVICES_HERO_BTN2_URL: 'services_hero_btn2_url',
  SERVICES_CAP_TITLE: 'services_cap_title',
  SERVICES_CAP_HIGHLIGHT: 'services_cap_highlight',
  SERVICES_CAP_BADGE: 'services_cap_badge',
  SERVICES_CAP_DESCRIPTION: 'services_cap_description',
  SERVICES_PROCESS_TITLE: 'services_process_title',
  SERVICES_PROCESS_BADGE: 'services_process_badge',
  SERVICES_PROCESS_DESCRIPTION: 'services_process_description',
  SERVICES_PROCESS_STEPS: 'services_process_steps',
  SERVICES_WHY_TITLE: 'services_why_title',
  SERVICES_WHY_BADGE: 'services_why_badge',
  SERVICES_WHY_DESCRIPTION: 'services_why_description',
  SERVICES_WHY_ITEMS: 'services_why_items',
  SERVICES_WHY_PROMISE_BADGE: 'services_why_promise_badge',
  SERVICES_WHY_PROMISE_QUOTE: 'services_why_promise_quote',
  SERVICES_WHY_PROMISE_AUTHOR: 'services_why_promise_author',
  SERVICES_WHY_PROMISE_SUB: 'services_why_promise_sub',
  SERVICES_WHY_PROMISE_TAGS: 'services_why_promise_tags',
  SERVICES_CTA_TITLE: 'services_cta_title',
  SERVICES_CTA_BADGE: 'services_cta_badge',
  SERVICES_CTA_DESCRIPTION: 'services_cta_description',
  SERVICES_CTA_BTN1_TEXT: 'services_cta_btn1_text',
  SERVICES_CTA_BTN1_URL: 'services_cta_btn1_url',
  SERVICES_CTA_BTN2_TEXT: 'services_cta_btn2_text',
  SERVICES_CTA_BTN2_URL: 'services_cta_btn2_url',
  SERVICES_WHAT_TITLE: 'services_what_title',
  SERVICES_WHAT_DESCRIPTION: 'services_what_description',
  SERVICES_WHAT_FEATURES: 'services_what_features',
  SERVICES_WHAT_IMAGES: 'services_what_images',
  HOME_SOLUTIONS_TITLE: 'home_solutions_title',
  HOME_SOLUTIONS_BADGE: 'home_solutions_badge',
  HOME_SOLUTIONS_DESCRIPTION: 'home_solutions_description',
  HOME_SOLUTIONS_ITEMS: 'home_solutions_items',
  HOME_SERVICES_TITLE: 'home_services_title',
  HOME_SERVICES_BADGE: 'home_services_badge',
  HOME_RECENT_WORK_TITLE: 'home_recent_work_title',
  HOME_RECENT_WORK_BADGE: 'home_recent_work_badge',
  HOME_RECENT_WORK_ITEMS: 'home_recent_work_items',
  HOME_VIDEO_URL: 'home_video_url',
  HOME_VIDEO_ENABLED: 'home_video_enabled',
  CONTACT_HERO_TITLE: 'contact_hero_title',
  CONTACT_HERO_DESCRIPTION: 'contact_hero_description',
  CONTACT_GLOBAL_PRESENCE_BADGE: 'contact_global_presence_badge',
  CONTACT_GLOBAL_PRESENCE_TITLE: 'contact_global_presence_title',
  CONTACT_BRANCH1_TITLE: 'contact_branch1_title',
  CONTACT_BRANCH1_ADDRESS: 'contact_branch1_address',
  CONTACT_BRANCH1_MAP_LINK: 'contact_branch1_map_link',
  CONTACT_BRANCH1_LAT_LONG: 'contact_branch1_lat_long',
  CONTACT_BRANCH1_MARKER_X: 'contact_branch1_marker_x',
  CONTACT_BRANCH1_MARKER_Y: 'contact_branch1_marker_y',
  CONTACT_BRANCH2_TITLE: 'contact_branch2_title',
  CONTACT_BRANCH2_ADDRESS: 'contact_branch2_address',
  CONTACT_BRANCH2_MAP_LINK: 'contact_branch2_map_link',
  CONTACT_BRANCH2_LAT_LONG: 'contact_branch2_lat_long',
  CONTACT_BRANCH2_MARKER_X: 'contact_branch2_marker_x',
  CONTACT_BRANCH2_MARKER_Y: 'contact_branch2_marker_y',
  CONTACT_BRANCH3_TITLE: 'contact_branch3_title',
  CONTACT_BRANCH3_ADDRESS: 'contact_branch3_address',
  CONTACT_BRANCH3_MAP_LINK: 'contact_branch3_map_link',
  CONTACT_BRANCH3_LAT_LONG: 'contact_branch3_lat_long',
  CONTACT_BRANCH3_MARKER_X: 'contact_branch3_marker_x',
  CONTACT_BRANCH3_MARKER_Y: 'contact_branch3_marker_y',
  CONTACT_SUPPORT_TITLE: 'contact_support_title',
  CONTACT_SUPPORT_DESCRIPTION: 'contact_support_description',
  CONTACT_SUPPORT_ITEM1_TITLE: 'contact_support_item1_title',
  CONTACT_SUPPORT_ITEM1_DESC: 'contact_support_item1_desc',
  CONTACT_SUPPORT_ITEM1_LINK: 'contact_support_item1_link',
  CONTACT_SUPPORT_ITEM2_TITLE: 'contact_support_item2_title',
  CONTACT_SUPPORT_ITEM2_DESC: 'contact_support_item2_desc',
  CONTACT_SUPPORT_ITEM2_LINK: 'contact_support_item2_link',
  CONTACT_SUPPORT_ITEM3_TITLE: 'contact_support_item3_title',
  CONTACT_SUPPORT_ITEM3_DESC: 'contact_support_item3_desc',
  CONTACT_SUPPORT_ITEM3_STATUS: 'contact_support_item3_status',
  CONTACT_FAQ_TITLE: 'contact_faq_title',
  CONTACT_FAQ_DESCRIPTION: 'contact_faq_description',
  CONTACT_FAQ1_QUESTION: 'contact_faq1_question',
  CONTACT_FAQ1_ANSWER: 'contact_faq1_answer',
  CONTACT_FAQ2_QUESTION: 'contact_faq2_question',
  CONTACT_FAQ2_ANSWER: 'contact_faq2_answer',
  CONTACT_FAQ3_QUESTION: 'contact_faq3_question',
  CONTACT_FAQ3_ANSWER: 'contact_faq3_answer',
  CONTACT_BRANCHES: 'contact_branches',
  ADMIN_NOTIFICATION_EMAIL: 'admin_notification_email',
  SMTP_HOST: 'smtp_host',
  SMTP_PORT: 'smtp_port',
  SMTP_USER: 'smtp_user',
  SMTP_PASS: 'smtp_pass',
  SMTP_FROM: 'smtp_from',
};

function settingsToForm(settings: any[]) {
  const map = new Map(settings.map((item) => [item.key, item.value]))

  const readString = (key: keyof typeof SETTINGS_KEYS, fallback: string) => {
    const value = map.get(SETTINGS_KEYS[key])
    return typeof value === 'string' ? value : fallback
  }

  const readNumber = (key: keyof typeof SETTINGS_KEYS, fallback: number) => {
    const value = map.get(SETTINGS_KEYS[key])
    const parsed = Number(value)
    return !Number.isNaN(parsed) && value !== undefined && value !== null ? parsed : fallback
  }

  return {
    ...DEFAULT_VALUES,
    maintenanceMode: map.get(SETTINGS_KEYS.MAINTENANCE_MODE) === true,
    maintenanceMessage: readString('MAINTENANCE_MESSAGE', DEFAULT_VALUES.maintenanceMessage),
    maintenanceEndTime: readString('MAINTENANCE_END_TIME', DEFAULT_VALUES.maintenanceEndTime),
    whatsappNumber: readString('WHATSAPP_NUMBER', DEFAULT_VALUES.whatsappNumber),
    internshipHeroTitle: readString('INTERNSHIP_HERO_TITLE', DEFAULT_VALUES.internshipHeroTitle),
    internshipHeroSubtitle: readString('INTERNSHIP_HERO_SUBTITLE', DEFAULT_VALUES.internshipHeroSubtitle),
    internshipHeroDescription: readString('INTERNSHIP_HERO_DESCRIPTION', DEFAULT_VALUES.internshipHeroDescription),
    internshipHeroImageUrl: readString('INTERNSHIP_HERO_IMAGE_URL', DEFAULT_VALUES.internshipHeroImageUrl),
    internshipIntroTitle: readString('INTERNSHIP_INTRO_TITLE', DEFAULT_VALUES.internshipIntroTitle),
    internshipIntroDescription: readString('INTERNSHIP_INTRO_DESCRIPTION', DEFAULT_VALUES.internshipIntroDescription),
    internshipApproachTitle: readString('INTERNSHIP_APPROACH_TITLE', DEFAULT_VALUES.internshipApproachTitle),
    internshipApproachDescription: readString('INTERNSHIP_APPROACH_DESCRIPTION', DEFAULT_VALUES.internshipApproachDescription),
    internshipCardOneValue: readString('INTERNSHIP_CARD_ONE_VALUE', DEFAULT_VALUES.internshipCardOneValue),
    internshipCardOneTitle: readString('INTERNSHIP_CARD_ONE_TITLE', DEFAULT_VALUES.internshipCardOneTitle),
    internshipCardOneDescription: readString('INTERNSHIP_CARD_ONE_DESCRIPTION', DEFAULT_VALUES.internshipCardOneDescription),
    internshipCardTwoValue: readString('INTERNSHIP_CARD_TWO_VALUE', DEFAULT_VALUES.internshipCardTwoValue),
    internshipCardTwoTitle: readString('INTERNSHIP_CARD_TWO_TITLE', DEFAULT_VALUES.internshipCardTwoTitle),
    internshipCardTwoDescription: readString('INTERNSHIP_CARD_TWO_DESCRIPTION', DEFAULT_VALUES.internshipCardTwoDescription),
    internshipCardThreeValue: readString('INTERNSHIP_CARD_THREE_VALUE', DEFAULT_VALUES.internshipCardThreeValue),
    internshipCardThreeTitle: readString('INTERNSHIP_CARD_THREE_TITLE', DEFAULT_VALUES.internshipCardThreeTitle),
    internshipCardThreeDescription: readString('INTERNSHIP_CARD_THREE_DESCRIPTION', DEFAULT_VALUES.internshipCardThreeDescription),
    internshipGalleryTitle: readString('INTERNSHIP_GALLERY_TITLE', DEFAULT_VALUES.internshipGalleryTitle),
    internshipGalleryImageUrls: readString('INTERNSHIP_GALLERY_IMAGE_URLS', DEFAULT_VALUES.internshipGalleryImageUrls),
    internshipTestimonialsTitle: readString('INTERNSHIP_TESTIMONIALS_TITLE', DEFAULT_VALUES.internshipTestimonialsTitle),
    internshipClosingTitle: readString('INTERNSHIP_CLOSING_TITLE', DEFAULT_VALUES.internshipClosingTitle),
    internshipClosingContent: readString('INTERNSHIP_CLOSING_CONTENT', DEFAULT_VALUES.internshipClosingContent),
    internshipApplyEmail: readString('INTERNSHIP_APPLY_EMAIL', DEFAULT_VALUES.internshipApplyEmail),
    labsHeroTitle: readString('LABS_HERO_TITLE', DEFAULT_VALUES.labsHeroTitle),
    labsHeroSubtitle: readString('LABS_HERO_SUBTITLE', DEFAULT_VALUES.labsHeroSubtitle),
    labsHeroDescription: readString('LABS_HERO_DESCRIPTION', DEFAULT_VALUES.labsHeroDescription),
    labsHeroImageUrl: readString('LABS_HERO_IMAGE_URL', DEFAULT_VALUES.labsHeroImageUrl),
    labsPageTitle: readString('LABS_PAGE_TITLE', DEFAULT_VALUES.labsPageTitle),
    labsPageSubtitle: readString('LABS_PAGE_SUBTITLE', DEFAULT_VALUES.labsPageSubtitle),
    labsHeroBtn1Text: readString('LABS_HERO_BTN1_TEXT', DEFAULT_VALUES.labsHeroBtn1Text),
    labsHeroBtn2Text: readString('LABS_HERO_BTN2_TEXT', DEFAULT_VALUES.labsHeroBtn2Text),
    labsIntroDescription: readString('LABS_INTRO_DESCRIPTION', DEFAULT_VALUES.labsIntroDescription),
    labsIntroImageUrl: readString('LABS_INTRO_IMAGE_URL', DEFAULT_VALUES.labsIntroImageUrl),
    labsIntroBtnText: readString('LABS_INTRO_BTN_TEXT', DEFAULT_VALUES.labsIntroBtnText),
    labsIntroFeature1Title: readString('LABS_INTRO_FEATURE1_TITLE', DEFAULT_VALUES.labsIntroFeature1Title),
    labsIntroFeature1Desc: readString('LABS_INTRO_FEATURE1_DESC', DEFAULT_VALUES.labsIntroFeature1Desc),
    labsIntroFeature2Title: readString('LABS_INTRO_FEATURE2_TITLE', DEFAULT_VALUES.labsIntroFeature2Title),
    labsIntroFeature2Desc: readString('LABS_INTRO_FEATURE2_DESC', DEFAULT_VALUES.labsIntroFeature2Desc),
    labsIntroFeature3Title: readString('LABS_INTRO_FEATURE3_TITLE', DEFAULT_VALUES.labsIntroFeature3Title),
    labsIntroFeature3Desc: readString('LABS_INTRO_FEATURE3_DESC', DEFAULT_VALUES.labsIntroFeature3Desc),
    labsIntroFeature4Title: readString('LABS_INTRO_FEATURE4_TITLE', DEFAULT_VALUES.labsIntroFeature4Title),
    labsIntroFeature4Desc: readString('LABS_INTRO_FEATURE4_DESC', DEFAULT_VALUES.labsIntroFeature4Desc),
    labsCareersTitle: readString('LABS_CAREERS_TITLE', DEFAULT_VALUES.labsCareersTitle),
    labsCareersDescription: readString('LABS_CAREERS_DESCRIPTION', DEFAULT_VALUES.labsCareersDescription),
    labsCareersBtnText: readString('LABS_CAREERS_BTN_TEXT', DEFAULT_VALUES.labsCareersBtnText),
    labsCtaTitle: readString('LABS_CTA_TITLE', DEFAULT_VALUES.labsCtaTitle),
    labsCtaDescription: readString('LABS_CTA_DESCRIPTION', DEFAULT_VALUES.labsCtaDescription),
    labsCtaBtnText: readString('LABS_CTA_BTN_TEXT', DEFAULT_VALUES.labsCtaBtnText),
    labsSpotlights: map.get(SETTINGS_KEYS.LABS_SPOTLIGHTS) || DEFAULT_VALUES.labsSpotlights,
    servicesHeroTitle: readString('SERVICES_HERO_TITLE', DEFAULT_VALUES.servicesHeroTitle),
    servicesHeroGradient: readString('SERVICES_HERO_GRADIENT', DEFAULT_VALUES.servicesHeroGradient),
    servicesHeroBadge: readString('SERVICES_HERO_BADGE', DEFAULT_VALUES.servicesHeroBadge),
    servicesHeroDescription: readString('SERVICES_HERO_DESCRIPTION', DEFAULT_VALUES.servicesHeroDescription),
    servicesHeroBtn1Text: readString('SERVICES_HERO_BTN1_TEXT', DEFAULT_VALUES.servicesHeroBtn1Text),
    servicesHeroBtn1Url: readString('SERVICES_HERO_BTN1_URL', DEFAULT_VALUES.servicesHeroBtn1Url),
    servicesHeroBtn2Text: readString('SERVICES_HERO_BTN2_TEXT', DEFAULT_VALUES.servicesHeroBtn2Text),
    servicesHeroBtn2Url: readString('SERVICES_HERO_BTN2_URL', DEFAULT_VALUES.servicesHeroBtn2Url),
    servicesCapTitle: readString('SERVICES_CAP_TITLE', DEFAULT_VALUES.servicesCapTitle),
    servicesCapHighlight: readString('SERVICES_CAP_HIGHLIGHT', DEFAULT_VALUES.servicesCapHighlight),
    servicesCapBadge: readString('SERVICES_CAP_BADGE', DEFAULT_VALUES.servicesCapBadge),
    servicesCapDescription: readString('SERVICES_CAP_DESCRIPTION', DEFAULT_VALUES.servicesCapDescription),
    servicesProcessTitle: readString('SERVICES_PROCESS_TITLE', DEFAULT_VALUES.servicesProcessTitle),
    servicesProcessBadge: readString('SERVICES_PROCESS_BADGE', DEFAULT_VALUES.servicesProcessBadge),
    servicesProcessDescription: readString('SERVICES_PROCESS_DESCRIPTION', DEFAULT_VALUES.servicesProcessDescription),
    servicesProcessSteps: map.get(SETTINGS_KEYS.SERVICES_PROCESS_STEPS) || DEFAULT_VALUES.servicesProcessSteps,
    servicesWhyTitle: readString('SERVICES_WHY_TITLE', DEFAULT_VALUES.servicesWhyTitle),
    servicesWhyBadge: readString('SERVICES_WHY_BADGE', DEFAULT_VALUES.servicesWhyBadge),
    servicesWhyDescription: readString('SERVICES_WHY_DESCRIPTION', DEFAULT_VALUES.servicesWhyDescription),
    servicesWhyItems: map.get(SETTINGS_KEYS.SERVICES_WHY_ITEMS) || DEFAULT_VALUES.servicesWhyItems,
    servicesWhyPromiseBadge: readString('SERVICES_WHY_PROMISE_BADGE', DEFAULT_VALUES.servicesWhyPromiseBadge),
    servicesWhyPromiseQuote: readString('SERVICES_WHY_PROMISE_QUOTE', DEFAULT_VALUES.servicesWhyPromiseQuote),
    servicesWhyPromiseAuthor: readString('SERVICES_WHY_PROMISE_AUTHOR', DEFAULT_VALUES.servicesWhyPromiseAuthor),
    servicesWhyPromiseSub: readString('SERVICES_WHY_PROMISE_SUB', DEFAULT_VALUES.servicesWhyPromiseSub),
    servicesWhyPromiseTags: readString('SERVICES_WHY_PROMISE_TAGS', DEFAULT_VALUES.servicesWhyPromiseTags),
    servicesCtaTitle: readString('SERVICES_CTA_TITLE', DEFAULT_VALUES.servicesCtaTitle),
    servicesCtaBadge: readString('SERVICES_CTA_BADGE', DEFAULT_VALUES.servicesCtaBadge),
    servicesCtaDescription: readString('SERVICES_CTA_DESCRIPTION', DEFAULT_VALUES.servicesCtaDescription),
    servicesCtaBtn1Text: readString('SERVICES_CTA_BTN1_TEXT', DEFAULT_VALUES.servicesCtaBtn1Text),
    servicesCtaBtn1Url: readString('SERVICES_CTA_BTN1_URL', DEFAULT_VALUES.servicesCtaBtn1Url),
    servicesCtaBtn2Text: readString('SERVICES_CTA_BTN2_TEXT', DEFAULT_VALUES.servicesCtaBtn2Text),
    servicesCtaBtn2Url: readString('SERVICES_CTA_BTN2_URL', DEFAULT_VALUES.servicesCtaBtn2Url),
    servicesWhatTitle: readString('SERVICES_WHAT_TITLE', DEFAULT_VALUES.servicesWhatTitle),
    servicesWhatDescription: readString('SERVICES_WHAT_DESCRIPTION', DEFAULT_VALUES.servicesWhatDescription),
    servicesWhatFeatures: map.get(SETTINGS_KEYS.SERVICES_WHAT_FEATURES) || DEFAULT_VALUES.servicesWhatFeatures,
    servicesWhatImages: map.get(SETTINGS_KEYS.SERVICES_WHAT_IMAGES) || DEFAULT_VALUES.servicesWhatImages,
    homeSolutionsTitle: readString('HOME_SOLUTIONS_TITLE', DEFAULT_VALUES.homeSolutionsTitle),
    homeSolutionsBadge: readString('HOME_SOLUTIONS_BADGE', DEFAULT_VALUES.homeSolutionsBadge),
    homeSolutionsDescription: readString('HOME_SOLUTIONS_DESCRIPTION', DEFAULT_VALUES.homeSolutionsDescription),
    homeSolutionsItems: map.get(SETTINGS_KEYS.HOME_SOLUTIONS_ITEMS) || DEFAULT_VALUES.homeSolutionsItems,
    homeServicesTitle: readString('HOME_SERVICES_TITLE', DEFAULT_VALUES.homeServicesTitle),
    homeServicesBadge: readString('HOME_SERVICES_BADGE', DEFAULT_VALUES.homeServicesBadge),
    homeRecentWorkTitle: readString('HOME_RECENT_WORK_TITLE', DEFAULT_VALUES.homeRecentWorkTitle),
    homeRecentWorkBadge: readString('HOME_RECENT_WORK_BADGE', DEFAULT_VALUES.homeRecentWorkBadge),
    homeRecentWorkItems: map.get(SETTINGS_KEYS.HOME_RECENT_WORK_ITEMS) || DEFAULT_VALUES.homeRecentWorkItems,
    homeVideoEnabled: map.get(SETTINGS_KEYS.HOME_VIDEO_ENABLED) === true,
    contactHeroTitle: readString('CONTACT_HERO_TITLE', DEFAULT_VALUES.contactHeroTitle),
    contactHeroDescription: readString('CONTACT_HERO_DESCRIPTION', DEFAULT_VALUES.contactHeroDescription),
    contactGlobalPresenceBadge: readString('CONTACT_GLOBAL_PRESENCE_BADGE', DEFAULT_VALUES.contactGlobalPresenceBadge),
    contactGlobalPresenceTitle: readString('CONTACT_GLOBAL_PRESENCE_TITLE', DEFAULT_VALUES.contactGlobalPresenceTitle),
    contactBranch1Title: readString('CONTACT_BRANCH1_TITLE', DEFAULT_VALUES.contactBranch1Title),
    contactBranch1Address: readString('CONTACT_BRANCH1_ADDRESS', DEFAULT_VALUES.contactBranch1Address),
    contactBranch1MapLink: readString('CONTACT_BRANCH1_MAP_LINK', DEFAULT_VALUES.contactBranch1MapLink),
    contactBranch1LatLong: readString('CONTACT_BRANCH1_LAT_LONG', DEFAULT_VALUES.contactBranch1LatLong),
    contactBranch1MarkerX: readNumber('CONTACT_BRANCH1_MARKER_X', DEFAULT_VALUES.contactBranch1MarkerX),
    contactBranch1MarkerY: readNumber('CONTACT_BRANCH1_MARKER_Y', DEFAULT_VALUES.contactBranch1MarkerY),
    contactBranch2Title: readString('CONTACT_BRANCH2_TITLE', DEFAULT_VALUES.contactBranch2Title),
    contactBranch2Address: readString('CONTACT_BRANCH2_ADDRESS', DEFAULT_VALUES.contactBranch2Address),
    contactBranch2MapLink: readString('CONTACT_BRANCH2_MAP_LINK', DEFAULT_VALUES.contactBranch2MapLink),
    contactBranch2LatLong: readString('CONTACT_BRANCH2_LAT_LONG', DEFAULT_VALUES.contactBranch2LatLong),
    contactBranch2MarkerX: readNumber('CONTACT_BRANCH2_MARKER_X', DEFAULT_VALUES.contactBranch2MarkerX),
    contactBranch2MarkerY: readNumber('CONTACT_BRANCH2_MARKER_Y', DEFAULT_VALUES.contactBranch2MarkerY),
    contactBranch3Title: readString('CONTACT_BRANCH3_TITLE', DEFAULT_VALUES.contactBranch3Title),
    contactBranch3Address: readString('CONTACT_BRANCH3_ADDRESS', DEFAULT_VALUES.contactBranch3Address),
    contactBranch3MapLink: readString('CONTACT_BRANCH3_MAP_LINK', DEFAULT_VALUES.contactBranch3MapLink),
    contactBranch3LatLong: readString('CONTACT_BRANCH3_LAT_LONG', DEFAULT_VALUES.contactBranch3LatLong),
    contactBranch3MarkerX: readNumber('CONTACT_BRANCH3_MARKER_X', DEFAULT_VALUES.contactBranch3MarkerX),
    contactBranch3MarkerY: readNumber('CONTACT_BRANCH3_MARKER_Y', DEFAULT_VALUES.contactBranch3MarkerY),
    contactSupportTitle: readString('CONTACT_SUPPORT_TITLE', DEFAULT_VALUES.contactSupportTitle),
    contactSupportDescription: readString('CONTACT_SUPPORT_DESCRIPTION', DEFAULT_VALUES.contactSupportDescription),
    contactSupportItem1Title: readString('CONTACT_SUPPORT_ITEM1_TITLE', DEFAULT_VALUES.contactSupportItem1Title),
    contactSupportItem1Desc: readString('CONTACT_SUPPORT_ITEM1_DESC', DEFAULT_VALUES.contactSupportItem1Desc),
    contactSupportItem1Link: readString('CONTACT_SUPPORT_ITEM1_LINK', DEFAULT_VALUES.contactSupportItem1Link),
    contactSupportItem2Title: readString('CONTACT_SUPPORT_ITEM2_TITLE', DEFAULT_VALUES.contactSupportItem2Title),
    contactSupportItem2Desc: readString('CONTACT_SUPPORT_ITEM2_DESC', DEFAULT_VALUES.contactSupportItem2Desc),
    contactSupportItem2Link: readString('CONTACT_SUPPORT_ITEM2_LINK', DEFAULT_VALUES.contactSupportItem2Link),
    contactSupportItem3Title: readString('CONTACT_SUPPORT_ITEM3_TITLE', DEFAULT_VALUES.contactSupportItem3Title),
    contactSupportItem3Desc: readString('CONTACT_SUPPORT_ITEM3_DESC', DEFAULT_VALUES.contactSupportItem3Desc),
    contactSupportItem3Status: readString('CONTACT_SUPPORT_ITEM3_STATUS', DEFAULT_VALUES.contactSupportItem3Status),
    contactFaqTitle: readString('CONTACT_FAQ_TITLE', DEFAULT_VALUES.contactFaqTitle),
    contactFaqDescription: readString('CONTACT_FAQ_DESCRIPTION', DEFAULT_VALUES.contactFaqDescription),
    contactFaq1Question: readString('CONTACT_FAQ1_QUESTION', DEFAULT_VALUES.contactFaq1Question),
    contactFaq1Answer: readString('CONTACT_FAQ1_ANSWER', DEFAULT_VALUES.contactFaq1Answer),
    contactFaq2Question: readString('CONTACT_FAQ2_QUESTION', DEFAULT_VALUES.contactFaq2Question),
    contactFaq2Answer: readString('CONTACT_FAQ2_ANSWER', DEFAULT_VALUES.contactFaq2Answer),
    contactFaq3Question: readString('CONTACT_FAQ3_QUESTION', DEFAULT_VALUES.contactFaq3Question),
    contactFaq3Answer: readString('CONTACT_FAQ3_ANSWER', DEFAULT_VALUES.contactFaq3Answer),
    adminNotificationEmail: readString('ADMIN_NOTIFICATION_EMAIL', ''),
    smtpHost: readString('SMTP_HOST', DEFAULT_VALUES.smtpHost),
    smtpPort: readString('SMTP_PORT', DEFAULT_VALUES.smtpPort),
    smtpUser: readString('SMTP_USER', DEFAULT_VALUES.smtpUser),
    smtpPass: readString('SMTP_PASS', DEFAULT_VALUES.smtpPass),
    smtpFrom: readString('SMTP_FROM', DEFAULT_VALUES.smtpFrom),
    contactBranches: (() => {
      const val = map.get(SETTINGS_KEYS.CONTACT_BRANCHES)
      if (Array.isArray(val)) return val
      if (typeof val === 'string') {
        try {
          return JSON.parse(val)
        } catch { }
      }
      return [];
    })()
  }
}

async function main() {
  const dbSettings = await prisma.setting.findMany();
  const formValues = settingsToForm(dbSettings);

  const result = settingsSchema.safeParse(formValues);
  if (result.success) {
    console.log("Validation SUCCESS!");
  } else {
    console.log("Validation FAILED:");
    console.log(JSON.stringify(result.error.flatten().fieldErrors, null, 2));
  }
}

main().catch(console.error);
