export const SETTINGS = {
  SITE_LOGO: "site_logo",
  MAINTENANCE_MODE: "maintenance_mode",
  MAINTENANCE_MESSAGE: "maintenance_message",
  MAINTENANCE_END_TIME: "maintenance_end_time",
  WHATSAPP_NUMBER: "whatsapp_number",
  ADMIN_NOTIFICATION_EMAIL: "admin_notification_email",

  // About Page
  ABOUT_WHO_TITLE: "aboutWhoTitle",
  ABOUT_WHO_DESCRIPTION: "aboutWhoDescription",
  ABOUT_WHO_SECONDARY_DESCRIPTION: "aboutWhoSecondaryDescription",
  ABOUT_WHO_FEATURES: "aboutWhoFeatures",
  ABOUT_WHO_IMAGES: "aboutWhoImages",
  ABOUT_PROCESS_BADGE: "aboutProcessBadge",
  ABOUT_PROCESS_TITLE: "aboutProcessTitle",
  ABOUT_PROCESS_FEATURES: "aboutProcessFeatures",
  ABOUT_PROCESS_IMAGE: "aboutProcessImage",
  ABOUT_MISSION_TITLE: "aboutMissionTitle",
  ABOUT_MISSION_DESC: "aboutMissionDesc",
  ABOUT_VISION_TITLE: "aboutVisionTitle",
  ABOUT_VISION_DESC: "aboutVisionDesc",
  ABOUT_MISSION_CARDS: "aboutMissionCards",
  ABOUT_CONTACT_BADGE: "aboutContactBadge",
  ABOUT_CONTACT_TITLE: "aboutContactTitle",
  ABOUT_CONTACT_IMAGE: "aboutContactImage",

  INTERNSHIP_HERO_TITLE: "internship_hero_title",
  INTERNSHIP_HERO_SUBTITLE: "internship_hero_subtitle",
  INTERNSHIP_HERO_DESCRIPTION: "internship_hero_description",
  INTERNSHIP_HERO_IMAGE_URL: "internship_hero_image_url",
  INTERNSHIP_INTRO_TITLE: "internship_intro_title",
  INTERNSHIP_INTRO_DESCRIPTION: "internship_intro_description",
  INTERNSHIP_APPROACH_TITLE: "internship_approach_title",
  INTERNSHIP_APPROACH_DESCRIPTION: "internship_approach_description",
  INTERNSHIP_CARD_ONE_VALUE: "internship_card_one_value",
  INTERNSHIP_CARD_ONE_TITLE: "internship_card_one_title",
  INTERNSHIP_CARD_ONE_DESCRIPTION: "internship_card_one_description",
  INTERNSHIP_CARD_TWO_VALUE: "internship_card_two_value",
  INTERNSHIP_CARD_TWO_TITLE: "internship_card_two_title",
  INTERNSHIP_CARD_TWO_DESCRIPTION: "internship_card_two_description",
  INTERNSHIP_CARD_THREE_VALUE: "internship_card_three_value",
  INTERNSHIP_CARD_THREE_TITLE: "internship_card_three_title",
  INTERNSHIP_CARD_THREE_DESCRIPTION: "internship_card_three_description",
  INTERNSHIP_GALLERY_TITLE: "internship_gallery_title",
  INTERNSHIP_GALLERY_IMAGE_URLS: "internship_gallery_image_urls",
  INTERNSHIP_TESTIMONIALS_TITLE: "internship_testimonials_title",
  INTERNSHIP_CLOSING_TITLE: "internship_closing_title",
  INTERNSHIP_CLOSING_CONTENT: "internship_closing_content",
  INTERNSHIP_APPLY_EMAIL: "internship_apply_email",
  INTERNSHIP_PROGRAMS: "internship_programs",
  INTERNSHIP_TESTIMONIALS: "internship_testimonials",
  // Labs – Hero
  LABS_HERO_TITLE: "labs_hero_title",
  LABS_HERO_SUBTITLE: "labs_hero_subtitle",
  LABS_HERO_DESCRIPTION: "labs_hero_description",
  LABS_HERO_IMAGE_URL: "labs_hero_image_url",
  LABS_HERO_BTN1_TEXT: "labs_hero_btn1_text",
  LABS_HERO_BTN2_TEXT: "labs_hero_btn2_text",
  // Labs – Intro
  LABS_PAGE_TITLE: "labs_page_title",
  LABS_PAGE_SUBTITLE: "labs_page_subtitle",
  LABS_INTRO_DESCRIPTION: "labs_intro_description",
  LABS_INTRO_IMAGE_URL: "labs_intro_image_url",
  LABS_INTRO_BTN_TEXT: "labs_intro_btn_text",
  LABS_INTRO_FEATURE1_TITLE: "labs_intro_feature1_title",
  LABS_INTRO_FEATURE1_DESC: "labs_intro_feature1_desc",
  LABS_INTRO_FEATURE2_TITLE: "labs_intro_feature2_title",
  LABS_INTRO_FEATURE2_DESC: "labs_intro_feature2_desc",
  LABS_INTRO_FEATURE3_TITLE: "labs_intro_feature3_title",
  LABS_INTRO_FEATURE3_DESC: "labs_intro_feature3_desc",
  LABS_INTRO_FEATURE4_TITLE: "labs_intro_feature4_title",
  LABS_INTRO_FEATURE4_DESC: "labs_intro_feature4_desc",
  // Labs – Spotlights
  LABS_SPOTLIGHTS: "labs_spotlights",
  // Labs – Careers
  LABS_CAREERS_TITLE: "labs_careers_title",
  LABS_CAREERS_DESCRIPTION: "labs_careers_description",
  LABS_CAREERS_BTN_TEXT: "labs_careers_btn_text",
  // Labs – CTA
  LABS_CTA_TITLE: "labs_cta_title",
  LABS_CTA_DESCRIPTION: "labs_cta_description",
  LABS_CTA_BTN_TEXT: "labs_cta_btn_text",

  // Labs – Initiatives, Rigor, Mentorship
  LABS_INITIATIVES: "labs_initiatives",
  LABS_RIGOR_TITLE: "labs_rigor_title",
  LABS_RIGOR_DESCRIPTION: "labs_rigor_description",
  LABS_RIGOR_POINTS: "labs_rigor_points",
  LABS_RIGOR_IMAGE: "labs_rigor_image",
  LABS_MENTORSHIP_TITLE: "labs_mentorship_title",
  LABS_MENTORSHIP_DESCRIPTION: "labs_mentorship_description",
  LABS_MENTORSHIP_IMAGE: "labs_mentorship_image",
  LABS_MENTORSHIP_QUOTE: "labs_mentorship_quote",
  LABS_MENTORSHIP_QUOTE_AUTHOR: "labs_mentorship_quote_author",
  LABS_MENTORSHIP_QUOTE_ROLE: "labs_mentorship_quote_role",
  LABS_MENTORSHIP_QUOTE_AVATAR: "labs_mentorship_quote_avatar",
  // Services – Hero
  SERVICES_HERO_TITLE: "services_hero_title",
  SERVICES_HERO_GRADIENT: "services_hero_gradient",
  SERVICES_HERO_BADGE: "services_hero_badge",
  SERVICES_HERO_DESCRIPTION: "services_hero_description",
  SERVICES_HERO_BTN1_TEXT: "services_hero_btn1_text",
  SERVICES_HERO_BTN1_URL: "services_hero_btn1_url",
  SERVICES_HERO_BTN2_TEXT: "services_hero_btn2_text",
  SERVICES_HERO_BTN2_URL: "services_hero_btn2_url",
  // Services – Capabilities Header
  SERVICES_CAP_TITLE: "services_cap_title",
  SERVICES_CAP_HIGHLIGHT: "services_cap_highlight",
  SERVICES_CAP_BADGE: "services_cap_badge",
  SERVICES_CAP_DESCRIPTION: "services_cap_description",
  // Services – Process Section
  SERVICES_PROCESS_TITLE: "services_process_title",
  SERVICES_PROCESS_BADGE: "services_process_badge",
  SERVICES_PROCESS_DESCRIPTION: "services_process_description",
  SERVICES_PROCESS_STEPS: "services_process_steps",
  // Services – Why Section
  SERVICES_WHY_TITLE: "services_why_title",
  SERVICES_WHY_BADGE: "services_why_badge",
  SERVICES_WHY_DESCRIPTION: "services_why_description",
  SERVICES_WHY_ITEMS: "services_why_items",
  SERVICES_WHY_PROMISE_BADGE: "services_why_promise_badge",
  SERVICES_WHY_PROMISE_QUOTE: "services_why_promise_quote",
  SERVICES_WHY_PROMISE_AUTHOR: "services_why_promise_author",
  SERVICES_WHY_PROMISE_SUB: "services_why_promise_sub",
  SERVICES_WHY_PROMISE_TAGS: "services_why_promise_tags",
  // Services – CTA Section
  SERVICES_CTA_TITLE: "services_cta_title",
  SERVICES_CTA_BADGE: "services_cta_badge",
  SERVICES_CTA_DESCRIPTION: "services_cta_description",
  SERVICES_CTA_BTN1_TEXT: "services_cta_btn1_text",
  SERVICES_CTA_BTN1_URL: "services_cta_btn1_url",
  SERVICES_CTA_BTN2_TEXT: "services_cta_btn2_text",
  SERVICES_CTA_BTN2_URL: "services_cta_btn2_url",

  // Services – What We Do Section
  SERVICES_WHAT_TITLE: "services_what_title",
  SERVICES_WHAT_DESCRIPTION: "services_what_description",
  SERVICES_WHAT_FEATURES: "services_what_features",
  SERVICES_WHAT_IMAGES: "services_what_images",

  // Home – Solutions Section
  HOME_SOLUTIONS_TITLE: "home_solutions_title",
  HOME_SOLUTIONS_BADGE: "home_solutions_badge",
  HOME_SOLUTIONS_DESCRIPTION: "home_solutions_description",
  HOME_SOLUTIONS_ITEMS: "home_solutions_items",

  // Home – Services & Recent Work Sections
  HOME_SERVICES_TITLE: "home_services_title",
  HOME_SERVICES_BADGE: "home_services_badge",
  HOME_RECENT_WORK_TITLE: "home_recent_work_title",
  HOME_RECENT_WORK_BADGE: "home_recent_work_badge",
  HOME_RECENT_WORK_ITEMS: "home_recent_work_items",

  // Contact – Hero & Presence
  CONTACT_HERO_TITLE: "contact_hero_title",
  CONTACT_HERO_DESCRIPTION: "contact_hero_description",
  CONTACT_GLOBAL_PRESENCE_BADGE: "contact_global_presence_badge",
  CONTACT_GLOBAL_PRESENCE_TITLE: "contact_global_presence_title",

  // Home Page Video
  HOME_VIDEO_URL: "home_video_url",
  HOME_VIDEO_ENABLED: "home_video_enabled",

  // Contact – Branch 1 (Cambridge)
  CONTACT_BRANCH1_TITLE: "contact_branch1_title",
  CONTACT_BRANCH1_ADDRESS: "contact_branch1_address",
  CONTACT_BRANCH1_MAP_LINK: "contact_branch1_map_link",
  CONTACT_BRANCH1_LAT_LONG: "contact_branch1_lat_long",
  CONTACT_BRANCH1_MARKER_X: "contact_branch1_marker_x",
  CONTACT_BRANCH1_MARKER_Y: "contact_branch1_marker_y",

  // Contact – Branch 2 (Bangalore)
  CONTACT_BRANCH2_TITLE: "contact_branch2_title",
  CONTACT_BRANCH2_ADDRESS: "contact_branch2_address",
  CONTACT_BRANCH2_MAP_LINK: "contact_branch2_map_link",
  CONTACT_BRANCH2_LAT_LONG: "contact_branch2_lat_long",
  CONTACT_BRANCH2_MARKER_X: "contact_branch2_marker_x",
  CONTACT_BRANCH2_MARKER_Y: "contact_branch2_marker_y",

  // Contact – Branch 3 (Chennai)
  CONTACT_BRANCH3_TITLE: "contact_branch3_title",
  CONTACT_BRANCH3_ADDRESS: "contact_branch3_address",
  CONTACT_BRANCH3_MAP_LINK: "contact_branch3_map_link",
  CONTACT_BRANCH3_LAT_LONG: "contact_branch3_lat_long",
  CONTACT_BRANCH3_MARKER_X: "contact_branch3_marker_x",
  CONTACT_BRANCH3_MARKER_Y: "contact_branch3_marker_y",

  // Contact – Support Channels
  CONTACT_SUPPORT_TITLE: "contact_support_title",
  CONTACT_SUPPORT_DESCRIPTION: "contact_support_description",
  CONTACT_SUPPORT_ITEM1_TITLE: "contact_support_item1_title",
  CONTACT_SUPPORT_ITEM1_DESC: "contact_support_item1_desc",
  CONTACT_SUPPORT_ITEM1_LINK: "contact_support_item1_link",
  CONTACT_SUPPORT_ITEM2_TITLE: "contact_support_item2_title",
  CONTACT_SUPPORT_ITEM2_DESC: "contact_support_item2_desc",
  CONTACT_SUPPORT_ITEM2_LINK: "contact_support_item2_link",
  CONTACT_SUPPORT_ITEM3_TITLE: "contact_support_item3_title",
  CONTACT_SUPPORT_ITEM3_DESC: "contact_support_item3_desc",
  CONTACT_SUPPORT_ITEM3_STATUS: "contact_support_item3_status",

  // Contact – FAQs Section
  CONTACT_FAQ_TITLE: "contact_faq_title",
  CONTACT_FAQ_DESCRIPTION: "contact_faq_description",
  CONTACT_FAQ1_QUESTION: "contact_faq1_question",
  CONTACT_FAQ1_ANSWER: "contact_faq1_answer",
  CONTACT_FAQ2_QUESTION: "contact_faq2_question",
  CONTACT_FAQ2_ANSWER: "contact_faq2_answer",
  CONTACT_FAQ3_QUESTION: "contact_faq3_question",
  CONTACT_FAQ3_ANSWER: "contact_faq3_answer",

  // Contact – Dynamic Branches List
  CONTACT_BRANCHES: "contact_branches",

  // SMTP Configuration
  SMTP_HOST: "smtp_host",
  SMTP_PORT: "smtp_port",
  SMTP_USER: "smtp_user",
  SMTP_PASS: "smtp_pass",
  SMTP_FROM: "smtp_from",
} as const;

export type SettingKey = (typeof SETTINGS)[keyof typeof SETTINGS];