import { prisma } from "../lib/prisma";
import { logAction } from "../utils/logAction";
import { AuditAction } from "../../generated/prisma/client";

import { settingKeySchema, settingSchemas } from "../validators/setting.validator";
import { httpError } from "../utils/httpError";
import { SETTINGS } from "../types/settings";
import { getPublicSiteConfig } from "./public.service";
import { emitSiteSettingsUpdated } from "../realtime/socket";

const realtimeSettingKeys: Set<string> = new Set([
  SETTINGS.MAINTENANCE_MODE,
  SETTINGS.MAINTENANCE_MESSAGE,
  SETTINGS.MAINTENANCE_END_TIME,
  SETTINGS.WHATSAPP_NUMBER,
  // Internship
  SETTINGS.INTERNSHIP_HERO_TITLE,
  SETTINGS.INTERNSHIP_HERO_SUBTITLE,
  SETTINGS.INTERNSHIP_HERO_DESCRIPTION,
  SETTINGS.INTERNSHIP_HERO_IMAGE_URL,
  SETTINGS.INTERNSHIP_INTRO_TITLE,
  SETTINGS.INTERNSHIP_INTRO_DESCRIPTION,
  SETTINGS.INTERNSHIP_APPROACH_TITLE,
  SETTINGS.INTERNSHIP_APPROACH_DESCRIPTION,
  SETTINGS.INTERNSHIP_CARD_ONE_VALUE,
  SETTINGS.INTERNSHIP_CARD_ONE_TITLE,
  SETTINGS.INTERNSHIP_CARD_ONE_DESCRIPTION,
  SETTINGS.INTERNSHIP_CARD_TWO_VALUE,
  SETTINGS.INTERNSHIP_CARD_TWO_TITLE,
  SETTINGS.INTERNSHIP_CARD_TWO_DESCRIPTION,
  SETTINGS.INTERNSHIP_CARD_THREE_VALUE,
  SETTINGS.INTERNSHIP_CARD_THREE_TITLE,
  SETTINGS.INTERNSHIP_CARD_THREE_DESCRIPTION,
  SETTINGS.INTERNSHIP_GALLERY_TITLE,
  SETTINGS.INTERNSHIP_GALLERY_IMAGE_URLS,
  SETTINGS.INTERNSHIP_TESTIMONIALS_TITLE,
  SETTINGS.INTERNSHIP_CLOSING_TITLE,
  SETTINGS.INTERNSHIP_CLOSING_CONTENT,
  SETTINGS.INTERNSHIP_APPLY_EMAIL,
  SETTINGS.INTERNSHIP_PROGRAMS,
  SETTINGS.INTERNSHIP_TESTIMONIALS,
  // Labs – Hero
  SETTINGS.LABS_HERO_TITLE,
  SETTINGS.LABS_HERO_SUBTITLE,
  SETTINGS.LABS_HERO_DESCRIPTION,
  SETTINGS.LABS_HERO_IMAGE_URL,
  SETTINGS.LABS_HERO_BTN1_TEXT,
  SETTINGS.LABS_HERO_BTN2_TEXT,
  // Labs – Intro
  SETTINGS.LABS_PAGE_TITLE,
  SETTINGS.LABS_PAGE_SUBTITLE,
  SETTINGS.LABS_INTRO_DESCRIPTION,
  SETTINGS.LABS_INTRO_IMAGE_URL,
  SETTINGS.LABS_INTRO_BTN_TEXT,
  SETTINGS.LABS_INTRO_FEATURE1_TITLE,
  SETTINGS.LABS_INTRO_FEATURE1_DESC,
  SETTINGS.LABS_INTRO_FEATURE2_TITLE,
  SETTINGS.LABS_INTRO_FEATURE2_DESC,
  SETTINGS.LABS_INTRO_FEATURE3_TITLE,
  SETTINGS.LABS_INTRO_FEATURE3_DESC,
  SETTINGS.LABS_INTRO_FEATURE4_TITLE,
  SETTINGS.LABS_INTRO_FEATURE4_DESC,
  // Labs – Spotlights
  SETTINGS.LABS_SPOTLIGHTS,
  // Labs – Careers
  SETTINGS.LABS_CAREERS_TITLE,
  SETTINGS.LABS_CAREERS_DESCRIPTION,
  SETTINGS.LABS_CAREERS_BTN_TEXT,
  // Labs – CTA
  SETTINGS.LABS_CTA_TITLE,
  SETTINGS.LABS_CTA_DESCRIPTION,
  SETTINGS.LABS_CTA_BTN_TEXT,
  // Labs – Initiatives, Rigor, Mentorship
  SETTINGS.LABS_INITIATIVES,
  SETTINGS.LABS_RIGOR_TITLE,
  SETTINGS.LABS_RIGOR_DESCRIPTION,
  SETTINGS.LABS_RIGOR_POINTS,
  SETTINGS.LABS_RIGOR_IMAGE,
  SETTINGS.LABS_MENTORSHIP_TITLE,
  SETTINGS.LABS_MENTORSHIP_DESCRIPTION,
  SETTINGS.LABS_MENTORSHIP_IMAGE,
  SETTINGS.LABS_MENTORSHIP_QUOTE,
  SETTINGS.LABS_MENTORSHIP_QUOTE_AUTHOR,
  SETTINGS.LABS_MENTORSHIP_QUOTE_ROLE,
  SETTINGS.LABS_MENTORSHIP_QUOTE_AVATAR,
  // Services – Hero
  SETTINGS.SERVICES_HERO_TITLE,
  SETTINGS.SERVICES_HERO_GRADIENT,
  SETTINGS.SERVICES_HERO_BADGE,
  SETTINGS.SERVICES_HERO_DESCRIPTION,
  SETTINGS.SERVICES_HERO_BTN1_TEXT,
  SETTINGS.SERVICES_HERO_BTN1_URL,
  SETTINGS.SERVICES_HERO_BTN2_TEXT,
  SETTINGS.SERVICES_HERO_BTN2_URL,
  // Services – Capabilities Header
  SETTINGS.SERVICES_CAP_TITLE,
  SETTINGS.SERVICES_CAP_HIGHLIGHT,
  SETTINGS.SERVICES_CAP_BADGE,
  SETTINGS.SERVICES_CAP_DESCRIPTION,
  // Services – Process Section
  SETTINGS.SERVICES_PROCESS_TITLE,
  SETTINGS.SERVICES_PROCESS_BADGE,
  SETTINGS.SERVICES_PROCESS_DESCRIPTION,
  SETTINGS.SERVICES_PROCESS_STEPS,
  // Services – Why Section
  SETTINGS.SERVICES_WHY_TITLE,
  SETTINGS.SERVICES_WHY_BADGE,
  SETTINGS.SERVICES_WHY_DESCRIPTION,
  SETTINGS.SERVICES_WHY_ITEMS,
  SETTINGS.SERVICES_WHY_PROMISE_BADGE,
  SETTINGS.SERVICES_WHY_PROMISE_QUOTE,
  SETTINGS.SERVICES_WHY_PROMISE_AUTHOR,
  SETTINGS.SERVICES_WHY_PROMISE_SUB,
  SETTINGS.SERVICES_WHY_PROMISE_TAGS,
  // Services – CTA Section
  SETTINGS.SERVICES_CTA_TITLE,
  SETTINGS.SERVICES_CTA_BADGE,
  SETTINGS.SERVICES_CTA_DESCRIPTION,
  SETTINGS.SERVICES_CTA_BTN1_TEXT,
  SETTINGS.SERVICES_CTA_BTN1_URL,
  SETTINGS.SERVICES_CTA_BTN2_TEXT,
  SETTINGS.SERVICES_CTA_BTN2_URL,

  // Home Solutions
  SETTINGS.HOME_SOLUTIONS_TITLE,
  SETTINGS.HOME_SOLUTIONS_BADGE,
  SETTINGS.HOME_SOLUTIONS_DESCRIPTION,
  SETTINGS.HOME_SOLUTIONS_ITEMS,

  // Home – Services & Recent Work
  SETTINGS.HOME_SERVICES_TITLE,
  SETTINGS.HOME_SERVICES_BADGE,
  SETTINGS.HOME_RECENT_WORK_TITLE,
  SETTINGS.HOME_RECENT_WORK_BADGE,
  SETTINGS.HOME_RECENT_WORK_ITEMS,

  // Home Page Video
  SETTINGS.HOME_VIDEO_URL,
  SETTINGS.HOME_VIDEO_ENABLED,

  // About Page
  SETTINGS.ABOUT_WHO_TITLE,
  SETTINGS.ABOUT_WHO_DESCRIPTION,
  SETTINGS.ABOUT_WHO_SECONDARY_DESCRIPTION,
  SETTINGS.ABOUT_WHO_FEATURES,
  SETTINGS.ABOUT_WHO_IMAGES,
  SETTINGS.ABOUT_PROCESS_BADGE,
  SETTINGS.ABOUT_PROCESS_TITLE,
  SETTINGS.ABOUT_PROCESS_FEATURES,
  SETTINGS.ABOUT_PROCESS_IMAGE,
  SETTINGS.ABOUT_MISSION_TITLE,
  SETTINGS.ABOUT_MISSION_DESC,
  SETTINGS.ABOUT_VISION_TITLE,
  SETTINGS.ABOUT_VISION_DESC,
  SETTINGS.ABOUT_MISSION_CARDS,
  SETTINGS.ABOUT_CONTACT_BADGE,
  SETTINGS.ABOUT_CONTACT_TITLE,
  SETTINGS.ABOUT_CONTACT_IMAGE,

  // Contact – Hero & Presence
  SETTINGS.CONTACT_HERO_TITLE,
  SETTINGS.CONTACT_HERO_DESCRIPTION,
  SETTINGS.CONTACT_GLOBAL_PRESENCE_BADGE,
  SETTINGS.CONTACT_GLOBAL_PRESENCE_TITLE,

  // Contact – Branch 1
  SETTINGS.CONTACT_BRANCH1_TITLE,
  SETTINGS.CONTACT_BRANCH1_ADDRESS,
  SETTINGS.CONTACT_BRANCH1_MAP_LINK,
  SETTINGS.CONTACT_BRANCH1_LAT_LONG,
  SETTINGS.CONTACT_BRANCH1_MARKER_X,
  SETTINGS.CONTACT_BRANCH1_MARKER_Y,

  // Contact – Branch 2
  SETTINGS.CONTACT_BRANCH2_TITLE,
  SETTINGS.CONTACT_BRANCH2_ADDRESS,
  SETTINGS.CONTACT_BRANCH2_MAP_LINK,
  SETTINGS.CONTACT_BRANCH2_LAT_LONG,
  SETTINGS.CONTACT_BRANCH2_MARKER_X,
  SETTINGS.CONTACT_BRANCH2_MARKER_Y,

  // Contact – Branch 3
  SETTINGS.CONTACT_BRANCH3_TITLE,
  SETTINGS.CONTACT_BRANCH3_ADDRESS,
  SETTINGS.CONTACT_BRANCH3_MAP_LINK,
  SETTINGS.CONTACT_BRANCH3_LAT_LONG,
  SETTINGS.CONTACT_BRANCH3_MARKER_X,
  SETTINGS.CONTACT_BRANCH3_MARKER_Y,

  // Contact – Support Channels
  SETTINGS.CONTACT_SUPPORT_TITLE,
  SETTINGS.CONTACT_SUPPORT_DESCRIPTION,
  SETTINGS.CONTACT_SUPPORT_ITEM1_TITLE,
  SETTINGS.CONTACT_SUPPORT_ITEM1_DESC,
  SETTINGS.CONTACT_SUPPORT_ITEM1_LINK,
  SETTINGS.CONTACT_SUPPORT_ITEM2_TITLE,
  SETTINGS.CONTACT_SUPPORT_ITEM2_DESC,
  SETTINGS.CONTACT_SUPPORT_ITEM2_LINK,
  SETTINGS.CONTACT_SUPPORT_ITEM3_TITLE,
  SETTINGS.CONTACT_SUPPORT_ITEM3_DESC,
  SETTINGS.CONTACT_SUPPORT_ITEM3_STATUS,

  // Contact – FAQs
  SETTINGS.CONTACT_FAQ_TITLE,
  SETTINGS.CONTACT_FAQ_DESCRIPTION,
  SETTINGS.CONTACT_FAQ1_QUESTION,
  SETTINGS.CONTACT_FAQ1_ANSWER,
  SETTINGS.CONTACT_FAQ2_QUESTION,
  SETTINGS.CONTACT_FAQ2_ANSWER,
  SETTINGS.CONTACT_FAQ3_QUESTION,
  SETTINGS.CONTACT_FAQ3_ANSWER,
  SETTINGS.HOME_VIDEO_URL,
  SETTINGS.HOME_VIDEO_ENABLED,
  SETTINGS.CONTACT_BRANCHES,
]);

const publishSiteSettingsUpdateIfNeeded = async (key: string) => {
  if (!realtimeSettingKeys.has(key)) {
    return;
  }

  const currentSiteConfig = await getPublicSiteConfig();
  emitSiteSettingsUpdated(currentSiteConfig as any);
};

export const validateSettingValue = (key: string, value: any) => {
  const parsedKey = settingKeySchema.safeParse(key);
  if (!parsedKey.success) {
    throw httpError(400, "Invalid setting key");
  }

  const schema = settingSchemas[parsedKey.data];
  const parsedValue = schema.safeParse(value);

  if (!parsedValue.success) {
    const firstIssue = parsedValue.error.issues[0];
    throw httpError(400, firstIssue?.message || "Invalid setting value");
  }

  return parsedValue.data;
};

export const upsertSetting = async (
  key: string,
  value: any,
  userId?: string
) => {
  const validKey = settingKeySchema.parse(key);
  const validValue = validateSettingValue(validKey, value);

  const existing = await prisma.setting.findUnique({
    where: { key: validKey },
  });

  const setting = await prisma.setting.upsert({
    where: { key: validKey },
    update: { value: validValue } as any,
    create: { key: validKey, value: validValue } as any,
  });

  await logAction({
    userId,
    action: existing ? AuditAction.UPDATE : AuditAction.CREATE,
    entity: "Setting",
    entityId: setting.id,
    oldData: existing,
    newData: setting,
  });

  await publishSiteSettingsUpdateIfNeeded(validKey);

  return setting;
};

export const getSetting = async (key: string) => {
  const validKey = settingKeySchema.parse(key);

  const setting = await prisma.setting.findUnique({
    where: { key: validKey },
  });

  if (!setting) {
    throw httpError(404, "Setting not found");
  }

  return setting;
};

export const getAllSettings = async () => {
  return prisma.setting.findMany({
    orderBy: { createdAt: "asc" },
  });
};

export const deleteSetting = async (key: string, userId?: string) => {
  const validKey = settingKeySchema.parse(key);

  const existing = await prisma.setting.findUnique({
    where: { key: validKey },
  });

  if (!existing) {
    throw httpError(404, "Setting not found");
  }

  await prisma.setting.delete({
    where: { key: validKey },
  });

  await logAction({
    userId,
    action: AuditAction.DELETE,
    entity: "Setting",
    entityId: existing.id,
    oldData: existing,
  });

  await publishSiteSettingsUpdateIfNeeded(validKey);

  return { success: true };
};